### PR TITLE
Replace Sidekiq with Sucker_Punch, Redis with Moneta

### PR DESCRIPTION
**Pull request by dometto**
Easy as a sandwich!

### CODE REVIEW

**Comment by dometto** [comment]
Using `rufus-scheduler` rather than `whenever` as a scheduling tool becomes it is mulithreaded and runs within the same process as the Sinatra app. This actually works! For testing purposes, use `scheduler.every('1m')` in `app.rb:106`. I've added logging so you can see the cron-like behavior functioning in `development.log` while the Sinatra app is running. :)

**Review by bartkamphorst — APPROVED** [review]
I like it!

**Comment by dometto** [comment]
Bit worried about memory consumption at the moment. The app takes up about ~110MB, which is fine, but it appears to grow by 1MB for each Worker I start (by hitting the `refresh` route), and that memory is not released after the job is done.

**Comment by bartkamphorst** [comment]
`GC.start`?

**Comment by dometto** [comment]
> GC.start?

Where?

**Comment by bartkamphorst** [comment]
Maybe try at the end of each worker's lifespan?

**Comment by bartkamphorst** [comment]
In Sucker Punch, there are 2 threads per Job by default (you can change this using the the `workers(num)` method). How many Jobs are you starting?

**Comment by dometto** [comment]
> How many Jobs are you starting?

Three in the example app. Then I assume one thread for rufus-scheduler (but maybe two) and one main thread makes 8 total. Not sure where the ninth comes from, and why the first manual refresh creates a 10th.

What I mostly don't understand is why it doesn't drop back to 5 threads after a Job is complete. But at least it doesn't keep going up after that.

**Pull request merged**
