### PR TITLE
Add method for building basic SVG badges.

### PR DESCRIPTION
**Pull request by bartkamphorst**
Run with `bundle exec ruby badge.rb` to generate three types of badges: up-to-date, out-of-date, unknown. Implements a method `build_badge(status)`.

Uses [Victor](https://github.com/DannyBen/victor) to generate the SVG images.

### CODE REVIEW

**Comment by dometto** [comment]
Very nice! I take it we can call `build_badge()` from Ruby (specifically, from Sidekiq), rather than having to use `bundle exec`?

**Review by dometto — APPROVED** [review]

**Comment by dometto** [comment]
Think it may be good to merge this before #2 to avoid merge conflicts.

**Comment by bartkamphorst** [comment]
> I  take it we can call build_badge() from Ruby (specifically, from Sidekiq), rather than having to use bundle exec?

We should probably put `build_badge(status, num)` into a class (e.g., `Badge`) that the workers can require and call (`Badge.build_badge(:out_of_date, 3)`).

**Comment by bartkamphorst** [comment]
The other question is what we want `build_badge` to return. Right now it returns a Victor object, but we could also have it return a filename or the rendered SVG. Thoughts?

**Comment by dometto** [comment]
> Right now it returns a Victor object, but we could also have it return a filename or the rendered SVG. Thoughts?

Depends a bit on the question of what backend we're going to use. If we stick with Redis, as I suggested (but can be persuaded otherwise!), we could just cache the SVG itself to Redis, and use [this gem](https://github.com/redis-store/redis-sinatra) to serve it.

**Comment by bartkamphorst** [comment]
> we could just cache the SVG itself to Redis

And by SVG you mean the rendered HTML or the SVG image (as file)?

**Comment by dometto** [comment]
> And by SVG you mean the rendered HTML or the SVG image (as file)?

I hadn't considered that actually. Either seems ok?

**Comment by bartkamphorst** [comment]
`svg.render` gives:
```html
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg width="180" height="32" 
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">


<rect x="0" y="0" width="180" height="32" fill="#32CD32" style="stroke:#d3d3d3; stroke-width:4"/>
<g font-size="14" font-family="arial" fill="white">
<text x="10" y="20">
 Dependencies up-to-date
</text>
</g>

</svg>
```

**Comment by bartkamphorst** [comment]
Actually, we can change the template to `:minimal` so that render only outputs the svg tag itself:
```html
<svg width="180" height="32">

<rect x="0" y="0" width="180" height="32" fill="#32CD32" style="stroke:#d3d3d3; stroke-width:4"/>
<g font-size="14" font-family="arial" fill="white">
<text x="10" y="20">
 Dependencies up-to-date
</text>
</g>
</svg>
```

**Comment by bartkamphorst** [comment]
We should probably also inspect existing svg badges like this one to mimick the look:
https://github.com/DannyBen/victor/workflows/Test/badge.svg

```html
<svg xmlns="http://www.w3.org/2000/svg" width="101" height="20">
  <defs>
    <linearGradient id="workflow-fill" x1="50%" y1="0%" x2="50%" y2="100%">
      <stop stop-color="#444D56" offset="0%"></stop>
      <stop stop-color="#24292E" offset="100%"></stop>
    </linearGradient>
    <linearGradient id="state-fill" x1="50%" y1="0%" x2="50%" y2="100%">
      <stop stop-color="#34D058" offset="0%"></stop>
      <stop stop-color="#28A745" offset="100%"></stop>
    </linearGradient>
  </defs>
  <g fill="none" fill-rule="evenodd">
    <g font-family="&#39;DejaVu Sans&#39;,Verdana,Geneva,sans-serif" font-size="11">
      <path id="workflow-bg" d="M0,3 C0,1.3431 1.3552,0 3.02702703,0 L51,0 L51,20 L3.02702703,20 C1.3552,20 0,18.6569 0,17 L0,3 Z" fill="url(#workflow-fill)" fill-rule="nonzero"></path>
      <text fill="#010101" fill-opacity=".3">
        <tspan x="22.1981982" y="15">Test</tspan>
      </text>
      <text fill="#FFFFFF">
        <tspan x="22.1981982" y="14">Test</tspan>
      </text>
    </g>
    <g transform="translate(51)" font-family="&#39;DejaVu Sans&#39;,Verdana,Geneva,sans-serif" font-size="11">
      <path d="M0 0h46.939C48.629 0 50 1.343 50 3v14c0 1.657-1.37 3-3.061 3H0V0z" id="state-bg" fill="url(#state-fill)" fill-rule="nonzero"></path>
      <text fill="#010101" fill-opacity=".3">
        <tspan x="4" y="15">passing</tspan>
      </text>
      <text fill="#FFFFFF">
        <tspan x="4" y="14">passing</tspan>
      </text>
    </g>
    <path fill="#959DA5" d="M11 3c-3.868 0-7 3.132-7 7a6.996 6.996 0 0 0 4.786 6.641c.35.062.482-.148.482-.332 0-.166-.01-.718-.01-1.304-1.758.324-2.213-.429-2.353-.822-.079-.202-.42-.823-.717-.99-.245-.13-.595-.454-.01-.463.552-.009.946.508 1.077.718.63 1.058 1.636.76 2.039.577.061-.455.245-.761.446-.936-1.557-.175-3.185-.779-3.185-3.456 0-.762.271-1.392.718-1.882-.07-.175-.315-.892.07-1.855 0 0 .586-.183 1.925.718a6.5 6.5 0 0 1 1.75-.236 6.5 6.5 0 0 1 1.75.236c1.338-.91 1.925-.718 1.925-.718.385.963.14 1.68.07 1.855.446.49.717 1.112.717 1.882 0 2.686-1.636 3.28-3.194 3.456.254.219.473.639.473 1.295 0 .936-.009 1.689-.009 1.925 0 .184.131.402.481.332A7.011 7.011 0 0 0 18 10c0-3.867-3.133-7-7-7z"></path>
  </g>
</svg>
```

**Comment by dometto** [comment]
> We should probably also inspect existing svg badges like this one to mimick the look:

I like the look of that one! But it is a little github-specific. I've just added support for gitlab repositories in #2. Or I guess that could be a configurable part of the badge?

In any case, those links basically serve HTML, so that's what we should be doing, too! :)

**Comment by dometto** [comment]
@bartkamphorst I would suggest the same here -- just merge this and keep working on it in smaller updates?

**Comment by bartkamphorst** [comment]
Sure, feel free to merge the whole shebang!

**Pull request merged**
