### PR TITLE
Alternative badge creation.

### PR DESCRIPTION
**Pull request by bartkamphorst**
Screen Shot 2020-04-13 at 15 26 52

### CODE REVIEW

**Comment by dometto** [comment]
Great, that's already looking much nicer! 😄 I think it would be nice if we could somehow integrate this information into a more classic button design, like the ones used [here](https://shields.io/category/dependencies) for example. Do you think that's at all doable? Otherwise we have two options:

* roll with our own design
* roll with the classic design, but just provide the detailed information in the `alt` text

(Or make the behavior optional for the user.)

**Comment by bartkamphorst** [comment]
Do you mean the rectangle (button-like) and background color scheme?

**Comment by dometto** [comment]
Yes, but we could also copy the color scheme (under the "Colors" heading [here](https://shields.io/) -- sorry, no anchor), although that's a detail. My main concern is that the badge looks nice next to a bunch of other badges on a Github/lab Readme.

**Comment by bartkamphorst** [comment]
> My main concern is that the badge looks nice next to a bunch of other badges on a Github/lab Readme.

Got it. But we keep the colored rings?

**Comment by dometto** [comment]
> Got it. But we keep the colored rings?

If that works, sure! Otherwise we could try rectangles or concatenating* various 'colored bits' of the badge?

*I mean: a 'normal' badge has one grey bit, and then a colored bit on the right -- could we have more than one colored bit, one for each kind of dependency?

**Pull request closed without merging**
