### PR TITLE
Better refresh

### PR DESCRIPTION
**Pull request by dometto**

### CODE REVIEW

**Comment by bartkamphorst** [comment]
Where's the refresh update commit?

**Comment by dometto** [comment]
Not sure which commit you mean! Did I forget something?

**Comment by bartkamphorst** [comment]
The title of the PR is 'Better refresh', but I can't seem to find any code changes related to the refresh route?

**Comment by dometto** [comment]
https://github.com/repotag/cutting_edge/pull/42/files#diff-ff199136e5e30b604ee9af84e9f1d037R106-R108 ? Or are we somehow not looking at the same code?

**Comment by bartkamphorst** [comment]
Never mind, I thought there would be something besides the way the token was dealt with. My bad.

**Pull request merged**
